{
    "openapi": "3.1.0",
    "info":{
        "title": "Motir√µ Study System - MSS",
        "description": "Class scheduling system.",
        "version": "1.0.0"
    },
    "servers": [
        {
          "url": "http://localhost:5000",
          "description": "API"
        }
    ],
    "paths": {
        "/instructor": {
            "post": {
                "summary": "Create a instructor",
                "description": "This route creates a new instructor",
                "tags": ["Instructor"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Instructor"
                            },
                            "examples": {
                                "instructor": {
                                    "value": {
                                        "name": "Peter Doe",
                                        "email": "peter@gmail.com",
                                        "password": "1S2G4Jds98",
                                        "specialty": ["Sciences", "Philosophy"],
                                        "schedule": [
                                            {
                                                "date": "2023-08-28 15:00",
                                                "busy": false
                                            },
                                            {
                                                "date": "2023-10-28 19:00",
                                                "busy": true
                                            }
                                        ],
                                        "role": ["instructor"]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "error": {
                                        "type": "string"
                                    }
                                },
                                "examples": {
                                    "Unauthorized": {
                                        "value": {
                                            "error": "Unauthorized, please authenticate"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "content": {
                          "application/json": {
                            "schema": {
                              "error": {
                                "type": "string"
                              }
                            },
                            "examples": {
                              "Not found": {
                                "value": {
                                  "error": "Instructor already exists or unfilled fields"
                                }
                              }
                            }
                          }
                        }
                    },
                    "201": {
                        "description": "Instructor created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                        "$ref":"#/components/schemas/Instructor"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "Get all instructors",
                "description": "This route get all instructors",
                "tags": ["Instructor"],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                "type": "object",
                                "$ref": "#/components/schemas/Instructor"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "error": {
                                        "type": "string"
                                    }
                                },
                                "examples": {
                                    "Unauthorized": {
                                        "value": {
                                            "error": "Unauthorized, please authenticate"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/instructor/{id}": {
            "get": {
                "summary": "Get one instructor by id",
                "description": "This route get one instructor by id",
                "tags": ["Instructor"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Instructor id for the search",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Instructor received",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type:": "object",
                                    "$ref":"#/components/schemas/Instructor"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "content": {
                          "application/json": {
                            "schema": {
                              "error": {
                                "type": "string"
                              }
                            },
                            "examples": {
                              "Instructor not found": {
                                "value": {
                                  "error": "No instructor with this id"
                                }
                              }
                            }
                          }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "error": {
                                        "type": "string"
                                    }
                                },
                                "examples": {
                                    "Unauthorized": {
                                        "value": {
                                            "error": "Unauthorized, please authenticate"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "summary": "Updates a instructor",
                "description": "This route updates a instructor by id",
                "tags": ["Instructor"],
                "parameters": [
                    {
                       "name": "id",
                       "in": "path",
                       "description": "Instructor id for update",
                       "required": true
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Instructor"
                            },
                            "examples": {
                                "instructor": {
                                    "value": {
                                        "name": "Peter Doe",
                                        "email": "peter@gmail.com",
                                        "password": "1S2G4Jds98",
                                        "specialty": ["Sciences", "Philosophy"],
                                        "schedule": [
                                            {
                                                "date": "2023-08-28 15:00",
                                                "busy": false
                                            },
                                            {
                                                "date": "2023-10-28 19:00",
                                                "busy": true
                                            }
                                        ],
                                        "role": ["instructor"]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Instructor updated",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type:": "object",
                                    "$ref":"#/components/schemas/Instructor"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "content": {
                          "application/json": {
                            "schema": {
                              "error": {
                                "type": "string"
                              }
                            },
                            "examples": {
                              "Instructor not found": {
                                "value": {
                                  "error": "No instructor with this id"
                                }
                              }
                            }
                          }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "error": {
                                        "type": "string"
                                    }
                                },
                                "examples": {
                                    "Unauthorized": {
                                        "value": {
                                            "error": "Unauthorized, please authenticate"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Delete a instructor",
                "description": "This route deletes a instructor",
                "tags": ["Instructor"],
                "parameters": [
                    {
                       "name": "id",
                       "in": "path",
                       "description": "Instructor id to be deleted",
                       "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Instructor deleted",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type:": "object",
                                    "$ref":"#/components/schemas/Instructor"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "content": {
                          "application/json": {
                            "schema": {
                              "error": {
                                "type": "string"
                              }
                            },
                            "examples": {
                              "Instructor not found": {
                                "value": {
                                  "error": "No instructor with this id"
                                }
                              }
                            }
                          }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "error": {
                                        "type": "string"
                                    }
                                },
                                "examples": {
                                    "Unauthorized": {
                                        "value": {
                                            "error": "Unauthorized, please authenticate"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/student": {
            "post": {
                "summary": "Create a student",
                "description": "This route creates a student",
                "tags": ["Student"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref":"#/components/schemas/Student"
                            },
                            "examples": {
                                "student": {
                                    "value": {
                                        "name": "Lucas Dionizio",
                                        "email": "lucas@gmail.com",
                                        "password":"1S2G4Jds98",
                                        "role": ["student"]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "error": {
                                        "type": "string"
                                      }
                                },
                                "examples": {
                                    "Unauthorized": {
                                        "value": {
                                            "error": "Unauthorized, please authenticate"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "content": {
                          "application/json": {
                            "schema": {
                              "error": {
                                "type": "string"
                              }
                            },
                            "examples": {
                              "Not found": {
                                "value": {
                                  "error": "Student already exists or unfilled fields"
                                }
                              }
                            }
                          }
                        }
                    },
                    "201": {
                        "description": "Student created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                        "$ref":"#/components/schemas/Student"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "Get all students",
                "description": "This route get all students",
                "tags": ["Student"],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                "type": "object",
                                "$ref": "#/components/schemas/Student"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "error": {
                                        "type": "string"
                                      }
                                },
                                "examples": {
                                    "Unauthorized": {
                                        "value": {
                                            "error": "Unauthorized, please authenticate"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/student/{id}": {
            "get": {
                "summary": "Get one student by id",
                "description": "This route get one student by id",
                "tags": ["Student"],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Student id for the search",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Student received",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type:": "object",
                                    "$ref":"#/components/schemas/Student"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "content": {
                          "application/json": {
                            "schema": {
                              "error": {
                                "type": "string"
                              }
                            },
                            "examples": {
                              "Student not found": {
                                "value": {
                                  "error": "No student with this id"
                                }
                              }
                            }
                          }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "error": {
                                        "type": "string"
                                    }
                                },
                                "examples": {
                                    "Unauthorized": {
                                        "value": {
                                            "error": "Unauthorized, please authenticate"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "summary": "Updates a student",
                "description": "This route updates a student by id",
                "tags": ["Student"],
                "parameters": [
                    {
                       "name": "id",
                       "in": "path",
                       "description": "Student id for update",
                       "required": true
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Student"
                            },
                            "examples": {
                                "instructor": {
                                    "value": {
                                        "name": "Lucas Dionizio",
                                        "email": "lucas@gmail.com",
                                        "password":"1S2G4Jds98",
                                        "role": ["student"]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Student updated",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type:": "object",
                                    "$ref":"#/components/schemas/Student"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "content": {
                          "application/json": {
                            "schema": {
                              "error": {
                                "type": "string"
                              }
                            },
                            "examples": {
                              "Student not found": {
                                "value": {
                                  "error": "No student with this id"
                                }
                              }
                            }
                          }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "error": {
                                        "type": "string"
                                      }
                                },
                                "examples": {
                                    "Unauthorized": {
                                        "value": {
                                            "error": "Unauthorized, please authenticate"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Delete a student",
                "description": "This route deletes a student",
                "tags": ["Student"],
                "parameters": [
                    {
                       "name": "id",
                       "in": "path",
                       "description": "Student id to be deleted",
                       "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Student deleted",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type:": "object",
                                    "$ref":"#/components/schemas/Student"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "content": {
                          "application/json": {
                            "schema": {
                              "error": {
                                "type": "string"
                              }
                            },
                            "examples": {
                              "Student not found": {
                                "value": {
                                  "error": "No student with this id"
                                }
                              }
                            }
                          }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "error": {
                                        "type": "string"
                                      }
                                },
                                "examples": {
                                    "Unauthorized": {
                                        "value": {
                                            "error": "Unauthorized, please authenticate"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }  
        }  
    },
    "components": {
        "schemas": {
            "Instructor": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    },
                    "specialty": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "schedule": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "date": {
                                    "type": "string"
                                },
                                "busy": {
                                    "type": "boolean"
                                }
                            }
                        }
                    },
                    "role": {
                        "type":"string",
                        "enum": ["instructor"]
                    }
                }
            },
            "Student": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    },
                    "role": {
                        "type":"string",
                        "enum": ["student"]
                    }
                }
            },
            "Lesson": {
                "type": "object",
                "properties": {
                    "instructor": {
                        "type": "string"
                    },
                    "student": {
                        "type": "string"
                    },
                    "date": {
                        "type": "string"
                    }
                }
            }
        }
    }
}